# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 085fd691ff501720e2fd5031fe97d0bb2e13ae90ef438bff18caa4dbcf482492337fa723241a99abb0cb419a677875be81006f71945a5caeca6dd533786ae5a3

test:
  secret_key_base: 198196c382730e910c11869682a177b4437851c394d2c1e18bf9f5634ea51d3c605fc021e1da2352c4965b1c3309ec9986fed6eb2cc61a44d71beaf806e6435b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
